image: docker:18.09
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
services: 
  - docker:18.09-dind
stages: 
  - Build
  - Push

before_script:
  - apk add python3
  - pip3 install awscli
  - docker load --input data/image.tar
  - $(aws ecr get-login --no-include-email --region ap-south-1)

Build: 
  stage: Build
  before_script: []
  script:
    - mkdir data/
    - docker build --compress -t proxy .
    - docker save --output data/image.tar proxy
  artifacts:
    name: image
    paths:
      - data/ 

Push Dev:
  stage: Push
  script:
    - docker tag proxy:latest $ECR_REPO:dev
    - docker push $ECR_REPO:dev
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

Push Release:
  stage: Push
  script:
    - echo $CI_COMMIT_TAG | sed 's/-release//'
    - export TAGGED_ECR=$ECR_REPO:$(echo $CI_COMMIT_TAG | sed 's/-release//')
    - docker tag proxy:latest $TAGGED_ECR_REPO
    - docker push $TAGGED_ECR_REPO
    - docker tag $TAGGED_ECR_REPO $ECR_REPO:latest
    - docker push $ECR_REPO:latest
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"
  
